### ISSUE TITLE
Security Certificate Invalid

### ISSUE THREAD

**Issue by TranceBlossom** [reustle/covid19japan#113]
@reustle the site's security certificate appears to be invalid

**Comment by reustle** [comment]
Strange, thanks for reporting. Looks fine on my end, and it's actually handled entirely by GitHub's systems. Would you mind sharing a screenshot of what you're seeing?

Thanks!

**Comment by TranceBlossom** [comment]
![image](https://user-images.githubusercontent.com/47022053/77494873-5a6f3080-6e8a-11ea-89af-729204edfe45.png)

If I click "Proceed Anyway," my workplace's web filtering system gives a message about the site being a phishing site and not allowing me to view it. Maybe that filtering system is causing the invalid security certificate error? It was working fine yesterday though, maybe the web filter got updated and for some reason your site is now blocked....

**Comment by liquidx** [comment]
The certificate is the same one we are serving (at least with the same expiry and issue dates), but maybe your browser is set to not trust the CA "Let's Encrypt"? 

<img width="505" alt="Screen Shot 2020-03-26 at 1 08 11" src="https://user-images.githubusercontent.com/72062/77558616-7ad8d280-6efe-11ea-93d0-46f7e2229bb4.png">


That would be odd though, because so many other sites use that CA.

**Comment by reustle** [comment]
Thanks again for reporting. Going to close this for now as we haven't received any other reports. Stay safe!
