### ISSUE TITLE
Age / Gender Data

### ISSUE THREAD

**Issue by reustle** [reustle/covid19japan#12]
Display age / gender information of the confirmed cases. This needs to be done with the patient data, and calculating it on the frontend.

Simple bar chart (stacked) https://c3js.org/samples/chart_bar_stacked.html

1. Include the 'patient data' sheet from the source spreadsheet into the cached json file that is generated every few minutes
2. Create a function to calculate the number of cases by gender / age bracket. The output will likely look something like this
``` javascript
[{
  ageBracket: 0, // Age 0-9
  maleCases: 13,
  femaleCases: 11
},{
  ageBracket: 10, // Age 10-19
  maleCases: 4,
  femaleCases: 7
},{
  ageBracket: 20, // Age 20-29
  maleCases: 27,
  femaleCases: 25
}]
```

3. Feed this new data into a newly created function `drawAgeDistributionGraph` which renders the stacked bar chart (Male and Female bars stacked per age bracket).

**Comment by Kay-Cube** [comment]
Two versions
I'm hesitating to whether to make a bar chart or not.
It's easier to check the ratio by bar chart, but we need to add 2 more colors for male/female.
Because existing blue/orange is visually linked to recovered/confirmed.
Adding two more colors will make this site super colorful
 
<img width="610" alt="Screen Shot 2020-02-22 at 17 12 12" src="https://user-images.githubusercontent.com/61060404/75088896-7c794880-5596-11ea-8221-6db8359ab140.png">

**Comment by reustle** [comment]
Looks nice! I think the second works out a bit better because for each of the 3 tabs, the columns would stay the same `Confirmed`, `Recovered`, `Deceased`. For the first one, I'm guessing the by Prefecture view would look as it does currently?

Regarding adding a chart, a table is at least a good start and we can go from there.

**Comment by Aeolun** [comment]
Hmm, I was also curious about this information, so I tried plotting the data for age/outcome, but it seems that a lot of information is actually missing for that, so the graph becomes super inaccurate (e.g. for most people we don't know if they're hospitalized, deceased or recovered).

<img width="518" alt="2020-04-12 22_42_01-(7285) Coronavirus Disease (COVID-19) Japan Tracker - Firefox Nightly" src="https://user-images.githubusercontent.com/1116482/79070199-2364a000-7d0f-11ea-97ad-5debdca29fb9.png">

**Comment by liquidx** [comment]
Yep, only about 20% of the confirmed cases we are tracking the status. It's pretty unreliable at the moment.

**Comment by pascal31415** [comment]
Hello, thank you very much for all of your hard work at covid19japan. I am a researcher and I have been making projections of the epidemic for the Saitama prefecture. I have been using covid19japan's data as it is the only source which has provided the age information of confirmed cases. This information is essential for making projections. However, since August 11, the age information is not available any more. Is it temporary, or have you decided to stop collecting it?

**Comment by Kay-Cube** [comment]
> Hello, thank you very much for all of your hard work at covid19japan. I am a researcher and I have been making projections of the epidemic for the Saitama prefecture. I have been using covid19japan's data as it is the only source which has provided the age information of confirmed cases. This information is essential for making projections. However, since August 11, the age information is not available any more. Is it temporary, or have you decided to stop collecting it?

Hi Pascal, it's great to know our website has been useful to you. Since beginning of August, there's been a big second wave of covid infections. With a small team we have, and everyone working voluntarily aside from their day job, we can't have all the information registered on our database. Sorry for the inconvenience. 

The original data of Saitama prefecture is from the prefectural site: https://www.pref.saitama.lg.jp/a0701/covid19/documents/itiran020826.pdf

**Comment by pascal31415** [comment]
Thank you for your reply. I completely understand, and again I am grateful for all the work you have done. We also tried before to gather the information from the prefectural site and links therein. But with a limited number of people, it proved impossible to extract enough data. Do you also extract the data by hand? We've been wondering if it is possible to develop some algorithm to extract it automatically.

**Comment by Kay-Cube** [comment]
Yea, we've been trying to automate some of the work, but a lot of prefectures have been using PDFs and delaying the update. We've been mostly validating the patients manually.
If you have a good method of extract the data automatically, would love to hear it!

**Comment by pascal31415** [comment]
Ok, so I just managed to extract the age data from the PDF file you indicated. Since the age data is already compiled in the PDF file itself, it was not too difficult. I just converted the PDF to a raw text file, then used some regular expressions to match the dates and age groups. I can give you the code if you like. I did it in Mathematica, but it can be done in any language like PERL.

The more difficult task I was mentioning is gathering data that is not already indicated in the PDF document itself, such as date of the onset of symptoms or date of death, etc. Such data is contained in the links which points to different PDF files originating from different agencies, with different formats. This is the data we tried to gather some time ago but it just take an infinite time to gather by hand. I wish we had a way to automate it but it looks very difficult.

One question: when this PDF file is updated, will it keep the same URL or change to a new one? When we looked at a previous version some time ago, I think it had a different URL.

**Comment by Kay-Cube** [comment]
> I can give you the code if you like. I did it in Mathematica, but it can be done in any language like PERL.

@liquidx @reustle Would the code help us automate some of the flow?

> The more difficult task I was mentioning is gathering data that is not already indicated in the PDF document itself, such as date of the onset of symptoms or date of death, etc. 

We share the same pain in gathering the data for deaths. For privacy reasons, some prefectures were not reporting the age, gender of the death patient, which makes it very difficult to track. Osaka was doing a good job in reporting information about deceased patients. If you're using the data for research reason, I wonder if you can contact the Saitama government for more data than shown on the website?

> One question: when this PDF file is updated, will it keep the same URL or change to a new one? When we looked at a previous version some time ago, I think it had a different URL.

The URL will be updated. For Saitama, the website is here: https://www.pref.saitama.lg.jp/a0701/covid19/jokyo.html

**Comment by reustle** [comment]
> Would the code help us automate some of the flow?

If we move more towards automating some of these processes (which seems to be an ideal direction), it would be helpful. Thanks!

**Comment by reustle** [comment]
I think this is no longer relevant for what we are / plan to show the users. Please re-open if you feel it should still be a goal.

@pascal31415 I hope you were able to find everything you needed in the PDF files!
