### ISSUE TITLE
Show number of cases and projections with logarithmic y-axis.

### ISSUE THREAD

**Issue by aywander** [reustle/covid19japan#141]
@reustle , plotting `log(number_of_cases)` makes it easier to see whether cases are increasing exponentially or not. Doubling times can also be over-plotted as straight lines for comparisons, like [this example in ourworldindata.org](https://ourworldindata.org/coronavirus#are-deaths-increasing-at-different-rates-in-different-countries).

**Comment by reustle** [comment]
I've seen some trackers where you can switch between our current view and logarithmic. Thoughts @liquidx @l15n ?

**Comment by l15n** [comment]
Using the logarithmic scale has been on my mind for a while as well. Up until very recently, the cases in Japan were growing linearly, so it made sense to stay linear. While linear scale, its still easy to identify when a curve is shifting to be exponential. 

Here's what it looks like when logarithmic.

## Trend Chart for Japan

![Screen Shot 2020-03-30 at 10 26 13](https://user-images.githubusercontent.com/3714/77867218-51f36d00-7271-11ea-815c-0eb64b42d407.png)

Starting from 1.

## Trajectory Chart by prefecture

![Screen Shot 2020-03-30 at 10 28 27](https://user-images.githubusercontent.com/3714/77867209-4c962280-7271-11ea-87c7-5153ba3ac440.png)

Starting from 100

Note, c3.js is a little broken here because `type: "log"` is still buggy and doesn't calculate the data-level label positions properly.

----

I havent' figured out how to add guidelines to c3.js yet.

**Comment by aywander** [comment]
@l15n, you're right, both linear and logarithmic are useful. @reustle, A toggle would be indeed be great.

**Comment by aywander** [comment]
> Note, c3.js is a little broken here because type: "log" is still buggy and doesn't calculate the data-level label positions properly.

Here also, perhaps the easiest is just to create a parallel data set of the logarithm of the data and plot that on a linear y-axis.

**Comment by reustle** [comment]
Thanks @aywander - For now, we'll leave it as is. There are likely better ways to display the data, but I think high level trends are probably where we may end up. Appreciate taking the time to leave feedback.
