### ISSUE TITLE
Build for production and deploy with Github Actions

### ISSUE THREAD

**Issue by l15n** [reustle/covid19japan#142]
The current workflow for deployment is as follows:

- Execute `npm run build-prod` locally
- Commit changes in `docs` 
- Push to GH and send PR
- Merge PR

This works, but can be cumbersome if another PR has been merged first.

## An alternative: Github Actions

I haven't really used Github Actions much yet, but my understanding is that it now provides the ability to run CI/CD.

https://help.github.com/en/actions

Example: [Github Pages Deploy Action](https://github.com/marketplace/actions/deploy-to-github-pages)

Looks like it should be possible to run `npm run build-prod` and then send it to a a deployment branch for github pages.

@reustle What do you think?

Related: https://github.com/reustle/covid19japan/issues/127

**Comment by liquidx** [comment]
Good idea.

We'd have to ask people to revert their changes in docs/ before submitting the PR. I think it makes sense since I've started separating out my site regeneration from my PRs (when I remember). It may just be a small modification from this one that is doing the same thing for the data repo, checking in the generated file into docs/

https://github.com/reustle/covid19japan-data/blob/master/.github/workflows/update.yml

You still get conflicts when pulling/merging though because the local build still modifies the files in docs/ on your local checkout.

**Comment by l15n** [comment]
Conflicts won't be a problem if we reconfigure github pages to serve from a branch, and then put docs into `.gitignore` 

https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site

We can probably transition cleanly by getting the action running first, do an initial build, then switch publishing source. Then we can ignore docs from thereon out

**Comment by l15n** [comment]
I'll start work on this in my fork

**Comment by l15n** [comment]
Closing in favor of Netlify https://github.com/reustle/covid19japan/issues/170
