### ISSUE TITLE
Include time of "last updated."

### ISSUE THREAD

**Issue by mcaubrey** [reustle/covid19japan#5]
With how fast news about the virus changes, I think it would be useful to see not only the date of the last update, but also the time.

**Comment by reustle** [comment]
Hey @mcaubrey it's a very good point. I'm trying to think of the best way to handle this, as it doesn't seem Google Sheets supports any kind of automatic "last updated" flag. This might have to be some middleware service that checks for changes in the sheet and logs that.

Otherwise, it would be a manually set field somewhere on the sheet that any editor needs to update after each change.

Will keep thinking about it, open to other suggestions. Cheers!
